/**
 * Live validiertes Unternehmens-Verzeichnis.
 *
 * Quelle: alle URLs aus den hochgeladenen Portal-/Finance-/Tooling-Listen.
 * Jede Domain wurde per HTTP-Request live aufgeloest (Redirects gefolgt,
 * Status < 400). Nicht erreichbare oder erfundene Eintraege wurden entfernt.
 * Partner-Portale und Docs-Pfade sind ebenfalls live geprueft.
 *
 * Validierungslauf: 2026-08-08 — 472 verifizierte Domains.
 */

export type ValidatedEntry = {
  slug: string;
  name: string;
  url: string;
  category: string;
  status: number;
  partnerPortal?: string;
  docs?: string;
};

export const validatedDirectory: ValidatedEntry[] = [
  {"slug": "abax-fund", "name": "Abax", "url": "https://abax.fund", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://abax.fund/partners", "docs": "https://abax.fund/docs"},
  {"slug": "academy-binance-com", "name": "Academy", "url": "https://www.binance.com/en/academy", "category": "Ecosystem & Portale", "status": 202, "partnerPortal": "https://www.binance.com/en/academy/partners", "docs": "https://www.binance.com/en/academy/docs"},
  {"slug": "ag2-ai", "name": "AG2: Build Systems, Not Prompts", "url": "https://www.ag2.ai", "category": "AI & Agents", "status": 200, "docs": "https://docs.ag2.ai"},
  {"slug": "agent0-ai", "name": "agent0.ai", "url": "https://agent0.ai", "category": "AI & Agents", "status": 200},
  {"slug": "agent37-com", "name": "Managed OpenClaw & Hermes Hosting from $3.99/mo", "url": "https://www.agent37.com", "category": "Cloud & Infrastructure", "status": 200, "docs": "https://www.agent37.com/docs"},
  {"slug": "agentbank-com", "name": "AgentBank", "url": "https://www.agentbank.com", "category": "Finance & Banking", "status": 200, "docs": "https://www.agentbank.com/docs"},
  {"slug": "agno-com", "name": "Agno", "url": "https://www.agno.com", "category": "AI & Agents", "status": 200, "docs": "https://docs.agno.com"},
  {"slug": "ai-google-dev", "name": "Gemini Developer API", "url": "https://ai.google.dev", "category": "AI & Agents", "status": 200, "docs": "https://ai.google.dev/gemini-api/docs"},
  {"slug": "ai-pydantic-dev", "name": "Pydantic AI", "url": "https://pydantic.dev/docs/ai/overview", "category": "AI & Agents", "status": 200},
  {"slug": "aibars-net", "name": "AI News, AI Agents, Tools & Open Source LLM Rankings", "url": "https://aibars.net/en", "category": "AI & Agents", "status": 200},
  {"slug": "aicoolies-com", "name": "aicoolies", "url": "https://aicoolies.com", "category": "Developer Tools", "status": 200},
  {"slug": "aider-chat", "name": "Aider", "url": "https://aider.chat", "category": "AI & Agents", "status": 200, "docs": "https://aider.chat/docs"},
  {"slug": "airwallex-com", "name": "Airwallex: Trusted Global Payments & Financial Platform", "url": "https://www.airwallex.com:443/en-eu", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://www.airwallex.com:443/en-eu/partners"},
  {"slug": "aitoollab-cn", "name": "AI工具宝箱", "url": "https://www.aitoollab.cn", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "aitooltier-com", "name": "AIToolTier", "url": "https://aitooltier.com", "category": "AI & Agents", "status": 200},
  {"slug": "aleph-alpha-com", "name": "Aleph Alpha", "url": "https://aleph-alpha.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://aleph-alpha.com/en/#sectors", "docs": "https://docs.aleph-alpha.com"},
  {"slug": "allianz-fuer-cybersicherheit-de", "name": "ACS", "url": "https://www.allianz-fuer-cybersicherheit.de/Webs/ACS/DE/Home/home_node.html", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.allianz-fuer-cybersicherheit.de/Webs/ACS/DE/Home/home_node.html/partners", "docs": "https://www.allianz-fuer-cybersicherheit.de/Webs/ACS/DE/Home/home_node.html/docs"},
  {"slug": "allianz-gegen-rechtsextremismus-de", "name": "Allianz gegen Rechtsextremismus: Startseite", "url": "https://www.allianz-gegen-rechtsextremismus.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "allianz-ch", "name": "Allianz", "url": "https://www.allianz.ch/de/privatkunden.html", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.allianz.ch/de/privatkunden.html/partners", "docs": "https://www.allianz.ch/de/privatkunden.html/docs"},
  {"slug": "alpha-ucits-com", "name": "Alpha UCITS", "url": "https://www.alpha-ucits.com", "category": "Developer Tools", "status": 200},
  {"slug": "also-com", "name": "ALSO Holding AG", "url": "https://www.also.com/ec/cms5/en_6000/6000", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "altrion-at", "name": "Altrion", "url": "https://altrion.at", "category": "Finance & Banking", "status": 200},
  {"slug": "americanprogress-org", "name": "Center for American Progress", "url": "https://www.americanprogress.org", "category": "Government & Institutions", "status": 200},
  {"slug": "amundi-com", "name": "Amundi", "url": "https://about.amundi.com", "category": "Finance & Banking", "status": 200},
  {"slug": "angellist-com", "name": "AngelList", "url": "https://www.angellist.com", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://www.angellist.com/partnerships", "docs": "https://docs.angellist.com/login?redirect=%2F"},
  {"slug": "anthropic-com", "name": "Home \\ Anthropic", "url": "https://www.anthropic.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://claude.com/partners/powered-by-claude", "docs": "https://platform.claude.com/docs/en/home"},
  {"slug": "anythingllm-com", "name": "AnythingLLM", "url": "https://anythingllm.com", "category": "AI & Agents", "status": 200, "docs": "https://docs.anythingllm.com"},
  {"slug": "apexgroup-com", "name": "Apex Group", "url": "https://www.apexgroup.com", "category": "Developer Tools", "status": 200},
  {"slug": "apnews-com", "name": "Apnews", "url": "https://apnews.com", "category": "Developer Tools", "status": 200},
  {"slug": "app-openi-tech", "name": "OpenI Hub", "url": "https://app.openi.tech", "category": "AI & Agents", "status": 200, "partnerPortal": "https://app.openi.tech/partners", "docs": "https://app.openi.tech/docs"},
  {"slug": "app-rwa-xyz", "name": "RWA.xyz", "url": "https://app.rwa.xyz", "category": "Finance & Banking", "status": 200},
  {"slug": "appsignal-com", "name": "AppSignal", "url": "https://www.appsignal.com", "category": "Observability & Monitoring", "status": 200, "docs": "https://docs.appsignal.com/getting-started"},
  {"slug": "aragon-org", "name": "Aragon", "url": "https://www.aragon.org", "category": "Tokenization & Web3", "status": 200, "docs": "https://docs.aragon.org"},
  {"slug": "arreltech-com", "name": "Institutional Digital Asset Infrastructure", "url": "https://arreltech.com", "category": "Finance & Banking", "status": 200},
  {"slug": "arxiv-org", "name": "arXiv.org e-Print archive", "url": "https://arxiv.org", "category": "Government & Institutions", "status": 200, "docs": "https://info.arxiv.org:443"},
  {"slug": "assure-co", "name": "Assure", "url": "https://spvconcierge.com", "category": "Developer Tools", "status": 200},
  {"slug": "atlas-initiative-de", "name": "Atlas-Initiative", "url": "https://www.atlas-initiative.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "atrocore-com", "name": "Atrocore", "url": "https://www.atrocore.com/en", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.atrocore.com/en/partner-program"},
  {"slug": "autonomy-work", "name": "The Autonomy Institute", "url": "https://autonomy.work", "category": "Ecosystem & Portale", "status": 200, "docs": "https://auth.autonomy.work"},
  {"slug": "awesome-python-com", "name": "Awesome Python", "url": "https://awesome-python.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "ayautomate-com", "name": "Best AI Transformation Partners", "url": "https://www.ayautomate.com", "category": "AI & Agents", "status": 200, "docs": "https://docs.ayautomate.com"},
  {"slug": "aystone-com", "name": "AYSTONE®", "url": "https://aystone.com", "category": "Developer Tools", "status": 200, "partnerPortal": "https://aystone.com/partners", "docs": "https://aystone.com/documentation"},
  {"slug": "b2broker-com", "name": "B2BROKER â¢ Prime of Prime Liquidity & Technology Provider", "url": "https://b2broker.com", "category": "Observability & Monitoring", "status": 200, "docs": "https://docs.b2broker.com"},
  {"slug": "baanx-com", "name": "Baanx Home", "url": "https://www.baanx.com", "category": "Finance & Banking", "status": 200, "docs": "https://docs.baanx.com/guides/introduction"},
  {"slug": "backed-fi", "name": "Backed Finance", "url": "https://backed.fi", "category": "Finance & Banking", "status": 200, "docs": "https://docs.xstocks.fi/docs"},
  {"slug": "bankless-com", "name": "Crypto News & Expert Analysis, Industry Leading Podcast", "url": "https://www.bankless.com", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://www.bankless.com/partners", "docs": "https://docs.bankless.com/bankless-api"},
  {"slug": "base-org", "name": "Base", "url": "https://www.base.org", "category": "Government & Institutions", "status": 200, "docs": "https://docs.base.org/get-started/base"},
  {"slug": "bcause-com", "name": "bcause", "url": "https://bcause.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "bcbgroup-com", "name": "Payment Infrastructure for Global Businesses", "url": "https://www.bcbgroup.com", "category": "Finance & Banking", "status": 200},
  {"slug": "bearingpoint-com", "name": "Management and Technology Consultancy", "url": "https://www.bearingpoint.com/en", "category": "Observability & Monitoring", "status": 200, "docs": "https://login.microsoftonline.com/aa321b6e-c2f4-42f8-95b8-4d018e6d28ec/oauth2/v2.0/authorize?redirect_uri=https%3A%2F%2Fdocs.bearingpoint.com%2Ftoken&response_type=code&response_mode=form_post&client_id=20654916-e557-458e-ad5f-9c980d268897&state=CUSTOM4SB-nVuoGkznHhRNJ3Zy4ej_KE4FQSXA%2Fdefault%2F&nonce=HKad-bkQxcTmxvdKIiiosVvxOAPZdDbb&scope=User.Read%20openid&x-client-SKU=passport-azure-ad&x-client-Ver=3.0.12"},
  {"slug": "benchlm-ai", "name": "LLM Leaderboard & AI Model Benchmarks", "url": "https://benchlm.ai", "category": "AI & Agents", "status": 200, "partnerPortal": "https://benchlm.ai/partners", "docs": "https://benchlm.ai/docs"},
  {"slug": "bertelsmann-stiftung-de", "name": "Startseite", "url": "https://www.bertelsmann-stiftung.de/de/startseite", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "beszel-dev", "name": "Beszel", "url": "https://beszel.dev", "category": "Observability & Monitoring", "status": 200},
  {"slug": "bgw-online-de", "name": "Startseite", "url": "https://www.bgw-online.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "bharatshakti-in", "name": "Bharatshakti", "url": "https://bharatshakti.in", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://bharatshakti.in/partnership-between-us-india-vital-for-stability-in-indo-pacific-us-army-chief-general-randy-george"},
  {"slug": "bitgo-com", "name": "Digital Asset Bank & Infrastructure for Institutions", "url": "https://www.bitgo.com", "category": "Finance & Banking", "status": 200},
  {"slug": "bitkom-org", "name": "Startseite Bitkom e. V.", "url": "https://www.bitkom.org", "category": "Government & Institutions", "status": 200},
  {"slug": "blackrock-com", "name": "Beleggingsbeheer en financiële diensten", "url": "https://www.blackrock.com/be", "category": "Developer Tools", "status": 200},
  {"slug": "blockbury-com", "name": "Blockbury Investment DAO", "url": "https://www.blockbury.com", "category": "Finance & Banking", "status": 200},
  {"slug": "blockchain-council-org", "name": "Blockchain Council", "url": "https://www.blockchain-council.org", "category": "Tokenization & Web3", "status": 200},
  {"slug": "blocksquare-io", "name": "Blocksquare", "url": "https://blocksquare.io", "category": "Tokenization & Web3", "status": 200, "partnerPortal": "https://blocksquare.io/partners", "docs": "https://docs.blocksquare.io"},
  {"slug": "blog-lista-org", "name": "Lista DAO", "url": "https://blog.lista.org", "category": "Tokenization & Web3", "status": 200},
  {"slug": "blog-tib-eu", "name": "TIB-Blog", "url": "https://blog.tib.eu", "category": "Observability & Monitoring", "status": 200},
  {"slug": "bnbchain-org", "name": "BNB Chain: Build for the Next Billion Web3 Users", "url": "https://www.bnbchain.org/en", "category": "Tokenization & Web3", "status": 200, "docs": "https://docs.bnbchain.org"},
  {"slug": "bny-com", "name": "BNY", "url": "https://www.bny.com/corporate/global/en.html", "category": "Developer Tools", "status": 200, "partnerPortal": "https://www.bny.com/corporate/global/en.html/partners", "docs": "https://www.bny.com/corporate/global/en.html/docs"},
  {"slug": "boeckler-de", "name": "Homepage", "url": "https://www.boeckler.de/de/index.htm", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "bolt-diy", "name": "GitHub", "url": "https://github.com/stackblitz-labs/bolt.diy", "category": "Cloud & Infrastructure", "status": 200},
  {"slug": "book-getfoundry-sh", "name": "Foundry", "url": "https://www.getfoundry.sh", "category": "Tokenization & Web3", "status": 200},
  {"slug": "brickken-com", "name": "Enterprise Tokenization Platform for Digital Assets", "url": "https://www.brickken.com", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://www.brickken.com/apply-partners", "docs": "https://docs.brickken.com"},
  {"slug": "broadcom-com", "name": "Broadcom Inc.", "url": "https://www.broadcom.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.broadcom.com/how-to-buy/partner-distributor-lookup", "docs": "https://www.broadcom.com/support/download-search"},
  {"slug": "bugsink-com", "name": "Bugsink: Self-hosted Error Tracking", "url": "https://www.bugsink.com", "category": "Cloud & Infrastructure", "status": 200, "docs": "https://www.bugsink.com/docs"},
  {"slug": "bundeswirtschaftsministerium-de", "name": "Bundesministerium für Wirtschaft und Energie", "url": "https://www.bundeswirtschaftsministerium.de/Navigation/DE/Home/home.html", "category": "Government & Institutions", "status": 200, "partnerPortal": "https://www.bundeswirtschaftsministerium.de/Navigation/DE/Home/home.html/partners", "docs": "https://www.bundeswirtschaftsministerium.de/Navigation/DE/Home/home.html/docs"},
  {"slug": "cacti-net", "name": "Cacti&reg;", "url": "https://cacti.net", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.cacti.net"},
  {"slug": "camel-ai-org", "name": "CAMEL-AI", "url": "https://camel-ai.org", "category": "Cloud & Infrastructure", "status": 200, "docs": "https://docs.camel-ai.org/get_started/introduction"},
  {"slug": "carnegroup-com", "name": "Carne", "url": "https://www.carnegroup.com", "category": "Developer Tools", "status": 200},
  {"slug": "casp-register-eu", "name": "MiCA CASP Register & CASP Licensing Support", "url": "https://casp-register.eu", "category": "Compliance & KYC", "status": 200},
  {"slug": "casptracker-eu", "name": "Casptracker", "url": "https://casptracker.eu", "category": "Compliance & KYC", "status": 200},
  {"slug": "cdn-tailwindcss-com", "name": "Cdn", "url": "https://cdn.tailwindcss.com/3.4.17", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "cdnjs-cloudflare-com", "name": "cdnjs.cloudflare.com", "url": "https://cdnjs.cloudflare.com", "category": "Cloud & Infrastructure", "status": 200},
  {"slug": "chainalysis-com", "name": "The Blockchain Data Platform", "url": "https://www.chainalysis.com", "category": "Tokenization & Web3", "status": 200, "partnerPortal": "https://www.chainalysis.com/partners"},
  {"slug": "chatbotui-com", "name": "Chatbot UI", "url": "https://www.chatbotui.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.chatbotui.com/partners", "docs": "https://www.chatbotui.com/docs"},
  {"slug": "chats-llm-com", "name": "Chat LLM", "url": "https://chats-llm.com/en", "category": "AI & Agents", "status": 200},
  {"slug": "checklyhq-com", "name": "Checkly", "url": "https://www.checklyhq.com", "category": "AI & Agents", "status": 200, "docs": "https://www.checklyhq.com/docs"},
  {"slug": "checkmk-com", "name": "Unified Hybrid & Cloud IT Observability", "url": "https://checkmk.com", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://checkmk.com/partners/find-partner", "docs": "https://docs.checkmk.com/latest/en"},
  {"slug": "cilium-io", "name": "Cilium", "url": "https://cilium.io", "category": "Observability & Monitoring", "status": 200, "docs": "https://docs.cilium.io/en/stable"},
  {"slug": "cinnalab-io", "name": "AI PRM Software for SaaS", "url": "https://cinnalab.io", "category": "AI & Agents", "status": 200, "partnerPortal": "https://cinnalab.io/partner-program"},
  {"slug": "citco-com", "name": "Homepage", "url": "https://www.citco.com", "category": "Developer Tools", "status": 200, "docs": "https://developer.citco.com/login"},
  {"slug": "citizenswealthfund-org", "name": "Citizens&#39; Wealth Fund", "url": "https://www.citizenswealthfund.org", "category": "Finance & Banking", "status": 200},
  {"slug": "claudemarket-ai", "name": "AI Agent Skills Directory", "url": "https://claudemarket.ai", "category": "AI & Agents", "status": 200},
  {"slug": "claw4science-org", "name": "Claw4Science", "url": "https://claw4science.org", "category": "Developer Tools", "status": 200, "docs": "https://claw4science.org/developers"},
  {"slug": "clawtank-dev", "name": "ClawTank", "url": "https://clawtank.dev", "category": "Cloud & Infrastructure", "status": 200, "partnerPortal": "https://clawtank.dev/login?callbackUrl=%2Fpartners", "docs": "https://clawtank.dev/docs"},
  {"slug": "clever-soft-com", "name": "Compliance Software for Financial Services", "url": "https://www.clever-soft.com", "category": "Compliance & KYC", "status": 200, "partnerPortal": "https://www.clever-soft.com/partnerships"},
  {"slug": "codersera-com", "name": "Hire vetted remote developers", "url": "https://codersera.com", "category": "Developer Tools", "status": 200},
  {"slug": "cohere-com", "name": "Cohere", "url": "https://cohere.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://cohere.com/partners", "docs": "https://docs.cohere.com"},
  {"slug": "coinshift-xyz", "name": "iUSPC", "url": "https://coinshift.xyz", "category": "Tokenization & Web3", "status": 200, "partnerPortal": "https://coinshift.xyz/partners", "docs": "https://docs.coinshift.xyz"},
  {"slug": "colony-io", "name": "Colony", "url": "https://www.colony.io", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://www.colony.io", "docs": "https://docs.colony.io"},
  {"slug": "commonwealth-ca", "name": "Common Wealth Canada", "url": "https://www.commonwealth.ca", "category": "Finance & Banking", "status": 200},
  {"slug": "complium-com", "name": "Complium", "url": "https://complium.com", "category": "Compliance & KYC", "status": 200},
  {"slug": "complybridge-xyz", "name": "ComplyBridge", "url": "https://complybridge.xyz", "category": "Compliance & KYC", "status": 200},
  {"slug": "complycube-com", "name": "Identity Verification, KYC & AML Platform", "url": "https://www.complycube.com/en", "category": "Compliance & KYC", "status": 200, "partnerPortal": "https://www.complycube.com/en/company/partner-program", "docs": "https://docs.complycube.com/documentation"},
  {"slug": "complyone-io", "name": "EU, UK & Swiss Compliance for SMBs & Data Centres", "url": "https://www.complyone.io", "category": "Compliance & KYC", "status": 200, "partnerPortal": "https://www.complyone.io/partners"},
  {"slug": "composio-dev", "name": "Composio", "url": "https://composio.dev", "category": "Developer Tools", "status": 200, "docs": "https://docs.composio.dev/docs"},
  {"slug": "continue-dev", "name": "Continue (acquired by Cursor)", "url": "https://continue.dev", "category": "Developer Tools", "status": 200, "docs": "https://docs.continue.dev"},
  {"slug": "copper-co", "name": "Leadership", "url": "https://copper.co/en-li/leadership-team", "category": "Finance & Banking", "status": 200, "docs": "https://developer.copper.co:443/guides/introduction"},
  {"slug": "cortexmetrics-io", "name": "Cortex", "url": "https://cortexmetrics.io", "category": "Observability & Monitoring", "status": 200, "docs": "https://cortexmetrics.io/docs"},
  {"slug": "coviah-com", "name": "Coviah", "url": "https://www.coviah.com", "category": "Compliance & KYC", "status": 200, "partnerPortal": "https://www.coviah.com/partners", "docs": "https://docs.coviah.com"},
  {"slug": "createdao-org", "name": "Createdao", "url": "https://createdao.org", "category": "Tokenization & Web3", "status": 200, "docs": "https://docs.createdao.org/introduction"},
  {"slug": "crewai-com", "name": "CrewAI", "url": "https://crewai.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.crewai.com"},
  {"slug": "crown-digital-co", "name": "Crown Digital Advisors", "url": "https://crown-digital.co", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://crown-digital.co/partners", "docs": "https://crown-digital.co/docs"},
  {"slug": "crymbo-com", "name": "Deploy Compliant Digital Asset Services", "url": "https://crymbo.com", "category": "Finance & Banking", "status": 200, "docs": "https://crymbo.com/resources"},
  {"slug": "currencycloud-com", "name": "International Payment Solutions & Infrastructure", "url": "https://www.currencycloud.com", "category": "Finance & Banking", "status": 200, "docs": "https://developer.currencycloud.com"},
  {"slug": "daohaus-club", "name": "DAOHaus", "url": "https://daohaus.club", "category": "Tokenization & Web3", "status": 200, "partnerPortal": "https://daohaus.club/partners", "docs": "https://docs.daohaus.club"},
  {"slug": "daohaus-com", "name": "daohaus.com is for sale. Buy it today!", "url": "https://www.domaineasy.com/buy-domain/daohaus.com", "category": "Tokenization & Web3", "status": 200},
  {"slug": "dash0-com", "name": "OpenTelemetry Native Observability · Dash0", "url": "https://www.dash0.com", "category": "Observability & Monitoring", "status": 200, "docs": "https://www.dash0.com/docs/dash0"},
  {"slug": "datadoghq-com", "name": "Cloud Monitoring as a Service", "url": "https://www.datadoghq.com", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://partners.datadoghq.com/s", "docs": "https://docs.datadoghq.com"},
  {"slug": "de-wikipedia-org", "name": "Wikipedia", "url": "https://de.wikipedia.org/wiki/Wikipedia:Hauptseite", "category": "Government & Institutions", "status": 200},
  {"slug": "deepinfra-com", "name": "Machine Learning Models and Infrastructure", "url": "https://deepinfra.com", "category": "Cloud & Infrastructure", "status": 200, "docs": "https://docs.deepinfra.com"},
  {"slug": "deine-domain-com", "name": "Deine Domain", "url": "https://deine-domain.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://deine-domain.com/partners", "docs": "https://deine-domain.com/docs"},
  {"slug": "denkstrom-org", "name": "Denkstrom", "url": "https://denkstrom.org", "category": "Government & Institutions", "status": 200},
  {"slug": "dertreasurer-de", "name": "DerTreasurer &#8211; Nachrichten für Finanzverantwortliche", "url": "https://www.dertreasurer.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.dertreasurer.de/partner"},
  {"slug": "dguv-de", "name": "Deutsche Gesetzliche Unfallversicherung", "url": "https://www.dguv.de/de/index.jsp", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "dify-ai", "name": "Dify", "url": "https://dify.ai", "category": "AI & Agents", "status": 200, "partnerPortal": "https://dify.ai/partners", "docs": "https://docs.dify.ai/en/home"},
  {"slug": "digishares-io", "name": "DigiShares", "url": "https://digishares.io", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "dl-gi-de", "name": "GI Digital Library", "url": "https://dl.gi.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "docs-daosquare-fi", "name": "DAOSquare Incubator Documentation", "url": "https://docs.daosquare.fi", "category": "Tokenization & Web3", "status": 200, "docs": "https://docs.daosquare.fi/documentation"},
  {"slug": "docs-ecdao-org", "name": "Welcome to Emerald City", "url": "https://docs.ecdao.org", "category": "Tokenization & Web3", "status": 200},
  {"slug": "docs-endaoment-org", "name": "What is Endaoment?", "url": "https://docs.endaoment.org/introduction", "category": "Tokenization & Web3", "status": 200},
  {"slug": "docs-mistral-ai", "name": "Documentation", "url": "https://docs.mistral.ai", "category": "AI & Agents", "status": 200, "docs": "https://docs.mistral.ai/developers"},
  {"slug": "docs-openeden-com", "name": "Welcome To OpenEden", "url": "https://docs.openeden.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.openeden.com/usdo/developers"},
  {"slug": "docs-rapyd-net", "name": "Docs", "url": "https://docs.rapyd.net", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://docs.rapyd.net/partners", "docs": "https://docs.rapyd.net/docs"},
  {"slug": "docs-reformdao-com", "name": "About Reform", "url": "https://docs.reformdao.com", "category": "Tokenization & Web3", "status": 200},
  {"slug": "documents1-worldbank-org", "name": "Documents & Reports", "url": "https://documents.worldbank.org/en/publication/documents-reports", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://login.microsoftonline.com/common/oauth2/authorize?resource=https://graph.windows.net&client_id=cf626b52-10a1-4150-8890-91a7f282d8f3&response_type=code&redirect_uri=https%3A%2F%2Fdocuments.worldbank.org%2Fetc%2Fcloudservices%2Fazureworldbankconnect%2Fstaging-azure-login-app.login.html%2Fcallback%2Fj_security_check&scope=&state=%7B%22n%22%3A%22u8tv3jb27lge2iiismtat5d3rc%22%2C%22r%22%3A%22%2Fen%2Fpublication%2Fdocuments-reports%2Fpartners%22%7D", "docs": "https://login.microsoftonline.com/common/oauth2/authorize?resource=https://graph.windows.net&client_id=cf626b52-10a1-4150-8890-91a7f282d8f3&response_type=code&redirect_uri=https%3A%2F%2Fdocuments.worldbank.org%2Fetc%2Fcloudservices%2Fazureworldbankconnect%2Fstaging-azure-login-app.login.html%2Fcallback%2Fj_security_check&scope=&state=%7B%22n%22%3A%22o1s0pq04qf3dd69oiou7jpb7ep%22%2C%22r%22%3A%22%2Fen%2Fpublication%2Fdocuments-reports%2Fdocs%22%7D"},
  {"slug": "docusign-com", "name": "Docusign", "url": "https://www.docusign.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.docusign.com/partners", "docs": "https://developers.docusign.com"},
  {"slug": "doi-org", "name": "Home Page", "url": "https://www.doi.org", "category": "Government & Institutions", "status": 200},
  {"slug": "doneinvestments-com", "name": "Done Investments", "url": "https://doneinvestments.com", "category": "Finance & Banking", "status": 200},
  {"slug": "dor-wa-gov", "name": "Dor", "url": "https://dor.wa.gov", "category": "Government & Institutions", "status": 200, "partnerPortal": "https://dor.wa.gov/open-business/business-licensing-service-and-local-licensing/combined-licensing-partnership-opportunities"},
  {"slug": "dowjones-com", "name": "Dow Jones", "url": "https://www.dowjones.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.dowjones.com/business-intelligence/partnership", "docs": "https://developer.dowjones.com"},
  {"slug": "dozzle-dev", "name": "Dozzle", "url": "https://dozzle.dev", "category": "Observability & Monitoring", "status": 200},
  {"slug": "dspy-ai", "name": "DSPy", "url": "https://dspy.ai", "category": "AI & Agents", "status": 200},
  {"slug": "dynatrace-com", "name": "Dynatrace", "url": "https://www.dynatrace.com", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://www.dynatrace.com/partners", "docs": "https://docs.dynatrace.com/docs"},
  {"slug": "e3holding-de", "name": "E3 Holding SE", "url": "https://e3holding.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://e3holding.de/partners", "docs": "https://e3holding.de/docs"},
  {"slug": "ebizprd-worldbank-org", "name": "eBusiness", "url": "https://ebizprd.worldbank.org", "category": "Finance & Banking", "status": 200},
  {"slug": "ec-europa-eu", "name": "Language selection", "url": "https://commission.europa.eu/select-language?destination=/node/1", "category": "Government & Institutions", "status": 200},
  {"slug": "eco-com", "name": "Eco: The Stablecoin Network That Makes Money Programmable", "url": "https://eco.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://eco.com/partners", "docs": "https://docs.eco.com/home"},
  {"slug": "econstor-eu", "name": "Making sure you&#39;re not a bot!", "url": "https://www.econstor.eu", "category": "Government & Institutions", "status": 200, "partnerPortal": "https://www.econstor.eu/partners", "docs": "https://www.econstor.eu/docs"},
  {"slug": "edgedelta-com", "name": "Wake Up to Root Causes", "url": "https://edgedelta.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://edgedelta.com/partners", "docs": "https://docs.edgedelta.com"},
  {"slug": "een-ec-europa-eu", "name": "Enterprise Europe Network", "url": "https://een.ec.europa.eu", "category": "Government & Institutions", "status": 200, "partnerPortal": "https://een.ec.europa.eu/partnering-opportunities"},
  {"slug": "effra-eu", "name": "EFFRA", "url": "https://www.effra.eu", "category": "Government & Institutions", "status": 200},
  {"slug": "eic-ec-europa-eu", "name": "Language selection", "url": "https://eic.ec.europa.eu/select-language?destination=/node/1", "category": "Developer Tools", "status": 200},
  {"slug": "eismea-ec-europa-eu", "name": "Language selection", "url": "https://eismea.ec.europa.eu/select-language?destination=/node/1", "category": "Developer Tools", "status": 200},
  {"slug": "eit-europa-eu", "name": "European Institute of Innovation & Technology (EIT)", "url": "https://www.eit.europa.eu", "category": "Observability & Monitoring", "status": 200},
  {"slug": "elt-de", "name": "Elt", "url": "https://edelstahl-mechanik.de/index.php/de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "endaoment-org", "name": "Charitable Giving & Donor-Advised Fund Platform", "url": "https://endaoment.org", "category": "Finance & Banking", "status": 200, "docs": "https://docs.endaoment.org/introduction"},
  {"slug": "enterpriseai-tools", "name": "Enterprise AI tools landscape tracker", "url": "https://www.enterpriseai.tools", "category": "AI & Agents", "status": 200},
  {"slug": "eqvista-com", "name": "Eqvista", "url": "https://eqvista.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://eqvista.com/partners", "docs": "https://eqvista.com"},
  {"slug": "esrs-services-de", "name": "ESG Plattform für Nachhaltigkeitsmanager", "url": "https://esrs-services.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://esrs-services.de/partnerschaft"},
  {"slug": "ethereum-org", "name": "Ethereum", "url": "https://ethereum.org", "category": "Tokenization & Web3", "status": 200, "docs": "https://ethereum.org/developers"},
  {"slug": "euenterprise-org", "name": "Build & Beyond", "url": "https://euenterprise.org", "category": "Developer Tools", "status": 200, "partnerPortal": "https://euenterprise.org/partners", "docs": "https://euenterprise.org/docs"},
  {"slug": "eurekanetwork-org", "name": "Eureka", "url": "https://www.eurekanetwork.org", "category": "Government & Institutions", "status": 200, "partnerPortal": "https://www.eurekanetwork.org/programmes-and-calls/innowwide/partner-search"},
  {"slug": "europa-eu", "name": "Language selection", "url": "https://european-union.europa.eu/select-language?destination=/node/1", "category": "Government & Institutions", "status": 200},
  {"slug": "eweb-io", "name": "EWEB.IO &#8211; Web Design Services", "url": "https://eweb.io", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "example-com", "name": "Example Domain", "url": "https://example.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "example-org", "name": "Example Domain", "url": "https://example.org", "category": "Government & Institutions", "status": 200},
  {"slug": "exoscale-com", "name": "European cloud provider Exoscale for modern infrastructure", "url": "https://www.exoscale.com", "category": "Cloud & Infrastructure", "status": 200},
  {"slug": "expertenallianz-gesundheit-de", "name": "Experten Allianz Sport, Fitness & Gesundheit", "url": "https://www.expertenallianz-gesundheit.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.expertenallianz-gesundheit.de/partner"},
  {"slug": "familienunternehmen-politik-de", "name": "Stiftung Familienunternehmen und Politik", "url": "https://www.familienunternehmen-politik.de/de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "faz-net", "name": "Aktuelle Nachrichten online", "url": "https://www.faz.net/aktuell", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "finmars-com", "name": "Finmars", "url": "https://finmars.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.finmars.com"},
  {"slug": "fipto-com", "name": "Fipto", "url": "https://www.fipto.com", "category": "Finance & Banking", "status": 200, "docs": "https://docs.fipto.com/reference/getting-started"},
  {"slug": "fireworks-ai", "name": "Own Your Specialized Intelligence", "url": "https://fireworks.ai", "category": "AI & Agents", "status": 200, "partnerPortal": "https://fireworks.ai/partners", "docs": "https://docs.fireworks.ai/getting-started/introduction"},
  {"slug": "firma-de", "name": "Einfach GrÃ¼nden", "url": "https://www.firma.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "firmenfreund-at", "name": "Firmenverzeichnis Österreich", "url": "https://firmenfreund.at", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "firstmilelabs-com", "name": "KYB Onboarding Software for Banks", "url": "https://www.firstmilelabs.com", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://www.firstmilelabs.com/partners", "docs": "https://www.firstmilelabs.com/docs"},
  {"slug": "fivenines-io", "name": "Server, Network, Uptime & Cron Monitoring in One Platform", "url": "https://fivenines.io", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://fivenines.io/partners", "docs": "https://docs.fivenines.io"},
  {"slug": "flowiseai-com", "name": "Flowise", "url": "https://flowiseai.com", "category": "AI & Agents", "status": 200, "docs": "https://docs.flowiseai.com"},
  {"slug": "fluentbit-io", "name": "fluentbit", "url": "https://fluentbit.io", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://fluentbit.io/partners", "docs": "https://docs.fluentbit.io/manual"},
  {"slug": "fluentd-org", "name": "Fluentd", "url": "https://www.fluentd.org", "category": "Observability & Monitoring", "status": 200, "docs": "https://docs.fluentd.org"},
  {"slug": "fourthline-com", "name": "Fourthline", "url": "https://www.fourthline.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.fourthline.com/docs/fourthline-docs"},
  {"slug": "franchise-next-com", "name": "Franchise Next", "url": "https://www.franchise-next.com/de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "franchiseportal-de", "name": "Franchise in Deutschland: 1.000 Geschäftsideen für dich!", "url": "https://www.franchiseportal.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "franklintempleton-com", "name": "Franklin Templeton", "url": "https://www.franklintempleton.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.franklintempleton.com/partners", "docs": "https://www.franklintempleton.com/docs"},
  {"slug": "franklintempleton-de", "name": "Franklintempleton", "url": "https://www.franklintempleton.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.franklintempleton.de/partners", "docs": "https://www.franklintempleton.de/docs"},
  {"slug": "freewillimpact-org", "name": "FreeWill Impact Fund", "url": "https://www.freewillimpact.org", "category": "Finance & Banking", "status": 200},
  {"slug": "fuer-gruender-de", "name": "Das Portal für Gründer: von der Idee bis zur Gründung", "url": "https://www.fuer-gruender.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.fuer-gruender.de/partner"},
  {"slug": "fund-xp-lu", "name": "Fund XP", "url": "https://fund-xp.lu", "category": "Compliance & KYC", "status": 200},
  {"slug": "fundschain-worldbank-org", "name": "FundsChain", "url": "https://fundschain.worldbank.org", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://fundschain.worldbank.org/partners", "docs": "https://fundschain.worldbank.org/docs"},
  {"slug": "fz-juelich-de", "name": "Forschungszentrum Jülich", "url": "https://www.fz-juelich.de/de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "galxe-com", "name": "Galxe", "url": "https://www.galxe.com", "category": "Tokenization & Web3", "status": 200, "docs": "https://docs.galxe.com/about/introduction"},
  {"slug": "gatus-io", "name": "Gatus: The Most Advanced Status Page For Developers", "url": "https://gatus.io", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://gatus.io/partners", "docs": "https://gatus.io/docs"},
  {"slug": "geeky-gadgets-com", "name": "Geeky Gadgets", "url": "https://www.geeky-gadgets.com", "category": "Observability & Monitoring", "status": 200, "docs": "https://www.geeky-gadgets.com/docs-gemini-connection"},
  {"slug": "gitcoin-co", "name": "Gitcoin", "url": "https://gitcoin.co", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://gitcoin.co/partner"},
  {"slug": "github-com", "name": "Github", "url": "https://github.com", "category": "Developer Tools", "status": 200, "partnerPortal": "https://github.com/partners", "docs": "https://docs.github.com/en"},
  {"slug": "gitlab-com", "name": "Finally, AI for the entire software lifecycle.", "url": "https://about.gitlab.com", "category": "AI & Agents", "status": 200, "partnerPortal": "https://about.gitlab.com/partners", "docs": "https://docs.gitlab.com"},
  {"slug": "glama-ai", "name": "The MCP Server Registry, Inspector & Gateway", "url": "https://glama.ai", "category": "Cloud & Infrastructure", "status": 200},
  {"slug": "glitchtip-com", "name": "Open Source Error Tracking", "url": "https://glitchtip.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://glitchtip.com/documentation"},
  {"slug": "globalriskalliance-com", "name": "Globalriskalliance", "url": "https://globalriskalliance.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://globalriskalliance.com/partnership", "docs": "https://globalriskalliance.com"},
  {"slug": "gocirvex-com", "name": "Cirvex", "url": "https://www.gocirvex.com", "category": "Compliance & KYC", "status": 200, "partnerPortal": "https://www.gocirvex.com/partners", "docs": "https://docs.gocirvex.com"},
  {"slug": "gofastmcp-com", "name": "FastMCP: The Framework for MCP", "url": "https://gofastmcp.com/getting-started/welcome", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "goji-investments", "name": "Goji", "url": "https://goji.investments", "category": "Finance & Banking", "status": 200},
  {"slug": "goldfinch-finance", "name": "Goldfinch", "url": "https://www.goldfinch.finance", "category": "Finance & Banking", "status": 200, "docs": "https://docs.goldfinch.finance/goldfinch"},
  {"slug": "google-com", "name": "Google", "url": "https://www.google.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.google.com/partners", "docs": "https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fdocs.google.com%2F&dsh=S1561671184%3A1786184191382460&emr=1&followup=https%3A%2F%2Fdocs.google.com%2F&osid=1&passive=1209600&flowName=WebLiteSignIn&flowEntry=ServiceLogin&ifkv=Ac50bxuPQPXlSYEEOoCRggyfOlKlHeWF1M_80sMye2e5kTjMIWIMIkCUogDtR8WVe3necyeaxkPTBg"},
  {"slug": "gotify-net", "name": "Gotify", "url": "https://gotify.net", "category": "Ecosystem & Portale", "status": 200, "docs": "https://gotify.net/docs"},
  {"slug": "gov-near-org", "name": "NEAR Forum", "url": "https://gov.near.org", "category": "Government & Institutions", "status": 200},
  {"slug": "governance-portal-v2-vercel-app", "name": "Maker Governance", "url": "https://governance-portal-v2.vercel.app", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "gpt4all-io", "name": "GPT4All", "url": "https://www.nomic.ai/gpt4all", "category": "AI & Agents", "status": 200, "docs": "https://docs.gpt4all.io"},
  {"slug": "grafana-com", "name": "Full-stack observability for the agentic era", "url": "https://grafana.com", "category": "Observability & Monitoring", "status": 200, "docs": "https://grafana.com/docs"},
  {"slug": "greenclimate-fund", "name": "The world’s climate fund for developing countries", "url": "https://www.greenclimate.fund", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://www.greenclimate.fund/partners"},
  {"slug": "grok-com", "name": "Grok", "url": "https://grok.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://grok.com/partners", "docs": "https://grok.com/docs"},
  {"slug": "groq-com", "name": "Groq is the premier neocloud for fast inference", "url": "https://groq.com", "category": "Cloud & Infrastructure", "status": 200, "partnerPortal": "https://groq.com/contact", "docs": "https://console.groq.com/docs/overview"},
  {"slug": "grrow-io", "name": "Grrow", "url": "https://grrow.io", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://grrow.io/partners", "docs": "https://grrow.io/docs"},
  {"slug": "haendlerbund-de", "name": "Händlerbund", "url": "https://www.haendlerbund.de/de", "category": "Government & Institutions", "status": 200},
  {"slug": "hardhat-org", "name": "Hardhat 3", "url": "https://hardhat.org", "category": "Government & Institutions", "status": 200, "docs": "https://hardhat.org/docs/getting-started"},
  {"slug": "hashnote-com", "name": "Hashnote", "url": "https://www.hashnote.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "haufe-de", "name": "Haufe. Intelligenz, die bewegt.", "url": "https://www.haufe.de:443", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "haystack-deepset-ai", "name": "Haystack", "url": "https://haystack.deepset.ai", "category": "AI & Agents", "status": 200, "docs": "https://docs.haystack.deepset.ai"},
  {"slug": "hazeltree-com", "name": "Hazeltree", "url": "https://hazeltree.com", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://hazeltree.com/partners"},
  {"slug": "healthchecks-io", "name": "Healthchecks.io: Cron Job Monitoring", "url": "https://healthchecks.io", "category": "Observability & Monitoring", "status": 200, "docs": "https://healthchecks.io/docs"},
  {"slug": "hedgey-finance", "name": "Hedgey", "url": "https://hedgey.finance", "category": "Finance & Banking", "status": 200},
  {"slug": "heise-de", "name": "heise online", "url": "https://www.heise.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "help-salesforce-com", "name": "Salesforce Help", "url": "https://help.salesforce.com/s/?language=en_US", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://help.salesforce.com/s/?language=en_US", "docs": "https://help.salesforce.com/s/?language=en_US"},
  {"slug": "helpnetsecurity-com", "name": "Cybersecurity News and Expert Analysis", "url": "https://www.helpnetsecurity.com:443", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.helpnetsecurity.com/2003/02/11/partners-healthcare-chooses-neoteris-to-deliver-instant-secure-access-to-medical-information", "docs": "https://www.helpnetsecurity.com/2017/03/27/docscom-sensitive-info"},
  {"slug": "highlight-io", "name": "highlight.io: The open source monitoring platform.", "url": "https://highlight.io", "category": "Observability & Monitoring", "status": 200, "docs": "https://docs.highlight.io"},
  {"slug": "hollaex-com", "name": "🛡️Award Winning White-label Exchange Software", "url": "https://www.hollaex.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.hollaex.com"},
  {"slug": "huggingface-co", "name": "Hugging Face", "url": "https://huggingface.co", "category": "AI & Agents", "status": 200, "partnerPortal": "https://huggingface.co/partner", "docs": "https://huggingface.co/docs"},
  {"slug": "hyground-ai", "name": "Self-Hosted AI SRE Agent for Europe", "url": "https://hyground.ai", "category": "Cloud & Infrastructure", "status": 200, "partnerPortal": "https://hyground.ai/partners"},
  {"slug": "hyperdx-io", "name": "HyperDX", "url": "https://www.hyperdx.io", "category": "Observability & Monitoring", "status": 200, "docs": "https://www.hyperdx.io/docs"},
  {"slug": "hypereal-tech", "name": "Infrastructure for AI Video & Image Gen", "url": "https://hypereal.cloud", "category": "Cloud & Infrastructure", "status": 200, "docs": "https://hypereal.cloud/docs"},
  {"slug": "i6eal-de", "name": "i6eal â KI-Studio fÃ¼r Automatisierung & eigene Modelle", "url": "https://i6eal.de", "category": "AI & Agents", "status": 200},
  {"slug": "iacf-org", "name": "Investable Asset Charitable Fund", "url": "https://iacf.org", "category": "Finance & Banking", "status": 200},
  {"slug": "iais-fraunhofer-de", "name": "Startseite", "url": "https://www.iais.fraunhofer.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "icinga-com", "name": "Open Source Monitoring for Complex IT Infrastructure| Icinga", "url": "https://icinga.com", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://icinga.com/company/partners", "docs": "https://icinga.com/docs"},
  {"slug": "ifo-de", "name": "Client Challenge", "url": "https://www.ifo.de/ifo-startseite", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.ifo.de/ifo-startseite/partners", "docs": "https://www.ifo.de/ifo-startseite/docs"},
  {"slug": "ifswf-org", "name": "Ifswf", "url": "https://ifswf.org", "category": "Government & Institutions", "status": 200},
  {"slug": "influxdata-com", "name": "InfluxData", "url": "https://www.influxdata.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.influxdata.com/partners", "docs": "https://docs.influxdata.com"},
  {"slug": "interoperable-europe-ec-europa-eu", "name": "Interoperable Europe Portal", "url": "https://interoperable-europe.ec.europa.eu", "category": "Government & Institutions", "status": 200},
  {"slug": "iqeq-com", "name": "Global Investor Services", "url": "https://iqeq.com", "category": "Finance & Banking", "status": 200, "docs": "https://login.microsoftonline.com/b03dec2e-a78d-4e2d-8ef8-6293fb4a768a/wsfed?wa=wsignin1.0&wtrealm=urn%3asharepoint%3afederationPROD&wctx=https%3a%2f%2fdocs.iqeq.com%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252F&wreply=https%3a%2f%2fdocs.iqeq.com%2f_trust%2fdefault.aspx"},
  {"slug": "jaegertracing-io", "name": "Jaeger", "url": "https://www.jaegertracing.io", "category": "Developer Tools", "status": 200, "docs": "https://www.jaegertracing.io/docs"},
  {"slug": "jan-ai", "name": "Jan", "url": "https://www.jan.ai", "category": "AI & Agents", "status": 200, "docs": "https://www.jan.ai/docs"},
  {"slug": "juicebox-money", "name": "Juicebox", "url": "https://juicebox.money", "category": "Finance & Banking", "status": 200, "docs": "https://docs.juicebox.money"},
  {"slug": "junipersquare-com", "name": "Junipersquare", "url": "https://www.junipersquare.com", "category": "Finance & Banking", "status": 200, "docs": "https://www.junipersquare.com"},
  {"slug": "kdan-partner-portal-vercel-app", "name": "KDAN Partner Portal", "url": "https://kdan-partner-portal.vercel.app", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://kdan-partner-portal.vercel.app/partners", "docs": "https://kdan-partner-portal.vercel.app/docs"},
  {"slug": "kdnuggets-com", "name": "Data Science, Machine Learning, AI & Analytics", "url": "https://www.kdnuggets.com", "category": "AI & Agents", "status": 200},
  {"slug": "khoj-dev", "name": "Khoj", "url": "https://khoj.dev", "category": "AI & Agents", "status": 200, "docs": "https://docs.khoj.dev"},
  {"slug": "klima-allianz-de", "name": "Willkommen", "url": "https://www.klima-allianz.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "klima-plattform-de", "name": "Unternehmensnetzwerk Klimaschutz", "url": "https://www.klima-plattform.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "kooperativa-sk", "name": "Kooperativa poisťovňa", "url": "https://kooperativa.sk", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "kortix-com", "name": "Kortix", "url": "https://kortix.com", "category": "AI & Agents", "status": 200, "partnerPortal": "https://kortix.com/auth?redirect=%2Fpartners", "docs": "https://kortix.com/docs"},
  {"slug": "kryeministri-rks-gov-net", "name": "Kryeministri &#8211; Zyra e Kryeministrit", "url": "https://kryeministri.rks-gov.net", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://kryeministri.rks-gov.net/news/partneriteti-me-iowa-n-eshte-partneritet-me-shba-te"},
  {"slug": "kubero-dev", "name": "Open-source Solution for Kubernetes Deployments", "url": "https://www.kubero.dev", "category": "Cloud & Infrastructure", "status": 200, "docs": "https://docs.kubero.dev"},
  {"slug": "kyriba-com", "name": "Proven solutions to elevate liquidity performance", "url": "https://www.kyriba.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.kyriba.com/partners", "docs": "https://developer.kyriba.com"},
  {"slug": "lafv-li", "name": "LAFV Liechtensteinischer Anlagefondsverband", "url": "https://www.lafv.li/de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "langchain-com", "name": "LangChain: Observe, Evaluate, and Deploy Reliable AI Agents", "url": "https://www.langchain.com", "category": "Tokenization & Web3", "status": 200, "docs": "https://docs.langchain.com"},
  {"slug": "langflow-org", "name": "Langflow", "url": "https://www.langflow.org", "category": "AI & Agents", "status": 200, "docs": "https://docs.langflow.org"},
  {"slug": "lbbw-am-de", "name": "Fonds", "url": "https://www.lbbw-am.de/start", "category": "Finance & Banking", "status": 200},
  {"slug": "learn-microsoft-com", "name": "Microsoft Learn: Build with answers in reach", "url": "https://learn.microsoft.com/en-us", "category": "Developer Tools", "status": 200, "partnerPortal": "https://learn.microsoft.com/en-us/partner-center/developer", "docs": "https://learn.microsoft.com/en-us/docs"},
  {"slug": "ledgy-com", "name": "Equity & Executive Compensation Management Software", "url": "https://ledgy.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.ledgy.com"},
  {"slug": "letta-com", "name": "Letta", "url": "https://www.letta.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.letta.com"},
  {"slug": "lexisnexis-com", "name": "Welcome to LexisNexis", "url": "https://www.lexisnexis.com/en-us/gateway.page", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.lexisnexis.com/en-us/gateway.page", "docs": "https://www.lexisnexis.com/en-us/gateway.page"},
  {"slug": "lexware-de", "name": "Buchhaltungssoftware von Lexware", "url": "https://www.lexware.de", "category": "AI & Agents", "status": 200, "partnerPortal": "https://www.lexware.de/partner"},
  {"slug": "librechat-ai", "name": "LibreChat", "url": "https://www.librechat.ai", "category": "AI & Agents", "status": 200, "docs": "https://www.librechat.ai/docs"},
  {"slug": "librenms-org", "name": "LibreNMS", "url": "https://www.librenms.org", "category": "Government & Institutions", "status": 200, "docs": "https://docs.librenms.org"},
  {"slug": "licentium-io", "name": "Licentium", "url": "https://www.licentium.io", "category": "Compliance & KYC", "status": 200},
  {"slug": "link-springer-com", "name": "Client Challenge", "url": "https://link.springer.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://link.springer.com/partners", "docs": "https://link.springer.com/docs"},
  {"slug": "litellm-ai", "name": "LiteLLM", "url": "https://www.litellm.ai", "category": "AI & Agents", "status": 200, "docs": "https://docs.litellm.ai"},
  {"slug": "llamaindex-ai", "name": "LlamaIndex", "url": "https://www.llamaindex.ai", "category": "AI & Agents", "status": 200, "partnerPortal": "https://www.llamaindex.ai", "docs": "https://developers.llamaindex.ai/python/framework"},
  {"slug": "lmmarketcap-com", "name": "Lmmarketcap", "url": "https://lmmarketcap.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://lmmarketcap.com/docs"},
  {"slug": "lmstudio-ai", "name": "LM Studio Bionic", "url": "https://lmstudio.ai", "category": "AI & Agents", "status": 200, "partnerPortal": "https://lmstudio.ai/partners", "docs": "https://lmstudio.ai/docs/app"},
  {"slug": "lmsys-org", "name": "LMSYS Org", "url": "https://www.lmsys.org", "category": "Government & Institutions", "status": 200},
  {"slug": "lobechat-com", "name": "Sign In", "url": "https://app.lobehub.com/signin?callbackUrl=https%3A%2F%2Fapp.lobehub.com%2F", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://app.lobehub.com/signin?callbackUrl=https%3A%2F%2Fapp.lobehub.com%2F/partners", "docs": "https://app.lobehub.com/signin?callbackUrl=https%3A%2F%2Fapp.lobehub.com%2F/docs"},
  {"slug": "lobehub-com", "name": "LobeHub", "url": "https://lobehub.com", "category": "AI & Agents", "status": 200, "docs": "https://lobehub.com/docs"},
  {"slug": "localai-io", "name": "LocalAI · Make AI run on every machine", "url": "https://localai.io", "category": "AI & Agents", "status": 200, "docs": "https://localai.io/docs"},
  {"slug": "login-gov", "name": "The public’s one account for government.", "url": "https://login.gov", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://login.gov/partners", "docs": "https://developers.login.gov"},
  {"slug": "manageengine-com", "name": "Manageengine", "url": "https://www.manageengine.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.manageengine.com/partner.html", "docs": "https://accounts.zoho.com/signin?servicename=ZApps&serviceurl=https%3A%2F%2Fdeveloper.manageengine.com%2Fmyworkspaces"},
  {"slug": "maple-finance", "name": "Maple Finance", "url": "https://maple.finance", "category": "Finance & Banking", "status": 200, "docs": "https://docs.maple.finance"},
  {"slug": "mastra-ai", "name": "TypeScript AI Framework for Agents and Apps", "url": "https://mastra.ai", "category": "AI & Agents", "status": 200, "docs": "https://mastra.ai/docs"},
  {"slug": "mem0-ai", "name": "Mem0", "url": "https://mem0.ai", "category": "AI & Agents", "status": 200, "docs": "https://docs.mem0.ai/introduction"},
  {"slug": "merklescience-com", "name": "The Predictive Crypto Risk & Intelligence Platform", "url": "https://www.merklescience.com", "category": "Tokenization & Web3", "status": 200, "partnerPortal": "https://www.merklescience.com/partners", "docs": "https://docs.merklescience.com/docs/ai-agent"},
  {"slug": "mero-tech", "name": "Mero", "url": "https://mero.tech", "category": "Finance & Banking", "status": 200},
  {"slug": "metaco-com", "name": "Financial Infrastructure & Blockchain Technology Solutions", "url": "https://ripple.com", "category": "Tokenization & Web3", "status": 200, "partnerPortal": "https://ripple.com/customers", "docs": "https://ripple.com/developer-resources"},
  {"slug": "micahub-net", "name": "Micahub", "url": "https://micahub.net", "category": "Compliance & KYC", "status": 200, "partnerPortal": "https://micahub.net/partners", "docs": "https://micahub.net/docs"},
  {"slug": "micascan-eu", "name": "MiCA SCAN", "url": "https://micascan.eu", "category": "Compliance & KYC", "status": 200, "partnerPortal": "https://micascan.eu/partners", "docs": "https://micascan.eu/docs"},
  {"slug": "micatracker-digital-euro-association-de", "name": "MiCAR Tracker", "url": "https://micatracker.digital-euro-association.de", "category": "Compliance & KYC", "status": 200, "partnerPortal": "https://micatracker.digital-euro-association.de/partners", "docs": "https://micatracker.digital-euro-association.de/docs"},
  {"slug": "microsoft-github-io", "name": "Microsoft on GitHub", "url": "https://microsoft.github.io", "category": "Developer Tools", "status": 200},
  {"slug": "mintlify-com", "name": "Mintlify", "url": "https://www.mintlify.com", "category": "AI & Agents", "status": 200, "docs": "https://www.mintlify.com/docs"},
  {"slug": "mitglieder-benefits-de", "name": "MitgliederBenefits", "url": "https://mitglieder-benefits.de", "category": "Ecosystem & Portale", "status": 200, "docs": "https://developer.mitglieder-benefits.de"},
  {"slug": "mmonit-com", "name": "M/Monit", "url": "https://mmonit.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://mmonit.com/documentation"},
  {"slug": "modelcontextprotocol-io", "name": "What is the Model Context Protocol (MCP)?", "url": "https://modelcontextprotocol.io/docs/2026-07-28/getting-started/intro", "category": "AI & Agents", "status": 200},
  {"slug": "moody-decade-277426-framer-app", "name": "AI Agents for the Enterprise", "url": "https://moody-decade-277426.framer.app", "category": "AI & Agents", "status": 200},
  {"slug": "mrkt30-com", "name": "MRKT3.0", "url": "https://mrkt30.com", "category": "AI & Agents", "status": 200},
  {"slug": "multis-xyz", "name": "Multis", "url": "https://multis.xyz/en-gb", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://multis.xyz/en-gb/partners", "docs": "https://multis.xyz/en-gb/docs"},
  {"slug": "n8n-io", "name": "AI Workflow Automation Platform", "url": "https://n8n.io", "category": "AI & Agents", "status": 200, "partnerPortal": "https://n8n.io/partners", "docs": "https://docs.n8n.io"},
  {"slug": "nagios-org", "name": "Nagios", "url": "https://www.nagios.org", "category": "Observability & Monitoring", "status": 200, "docs": "https://www.nagios.org"},
  {"slug": "netdata-cloud", "name": "Netdata: Monitoring and troubleshooting transformed", "url": "https://www.netdata.cloud", "category": "Observability & Monitoring", "status": 200, "docs": "https://learn.netdata.cloud"},
  {"slug": "netxms-com", "name": "NetXMS", "url": "https://netxms.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://netxms.com/documentation"},
  {"slug": "netxms-org", "name": "NetXMS", "url": "https://netxms.com", "category": "Government & Institutions", "status": 200, "docs": "https://docs.netxms.org"},
  {"slug": "newstime-joyn-de", "name": "Aktuelle News, Hintergründe & Livestreams", "url": "https://newstime.joyn.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "ngi-eu", "name": "Next Generation Internet", "url": "https://ngi.eu", "category": "Government & Institutions", "status": 200, "partnerPortal": "https://ngi.eu/error404", "docs": "https://ngi.eu/funded_solution/docspec-wasm"},
  {"slug": "ngoportal-usaid-gov", "name": "Ngoportal", "url": "https://ngoportal.usaid.gov", "category": "Government & Institutions", "status": 200},
  {"slug": "nobon-com", "name": "Nobon â Your deal workspace, live in 15 minutes", "url": "https://nobon.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.nobon.com"},
  {"slug": "nomic-ai", "name": "Nomic", "url": "https://www.nomic.ai", "category": "AI & Agents", "status": 200, "docs": "https://docs.nomic.ai"},
  {"slug": "novus-com", "name": "Portfolio Intelligence", "url": "https://www.novus.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "o-mega-ai", "name": "o-mega", "url": "https://o-mega.ai", "category": "AI & Agents", "status": 200, "docs": "https://o-mega.ai/docs"},
  {"slug": "ocorian-com", "name": "Global Asset Servicer", "url": "https://www.ocorian.com", "category": "Finance & Banking", "status": 200},
  {"slug": "odoo-com", "name": "Open Source ERP and CRM", "url": "https://www.odoo.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.odoo.com/partners", "docs": "https://docs.odoo.com/web/login?redirect=%2Fodoo%3F"},
  {"slug": "ollama-com", "name": "Ollama", "url": "https://ollama.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.ollama.com"},
  {"slug": "ondo-finance", "name": "Ondo Finance", "url": "https://ondo.finance", "category": "Finance & Banking", "status": 200, "docs": "https://docs.ondo.finance"},
  {"slug": "oneuptime-com", "name": "OneUptime", "url": "https://oneuptime.com", "category": "Observability & Monitoring", "status": 200, "docs": "https://oneuptime.com/docs/en/introduction/getting-started"},
  {"slug": "onino-io", "name": "White-Label Distribution & Tokenization Platform for EU", "url": "https://onino.io", "category": "Tokenization & Web3", "status": 200, "partnerPortal": "https://onino.io/partnerships", "docs": "https://docs.onino.io"},
  {"slug": "oobabooga-github-io", "name": "oobabooga.github.io", "url": "https://oobabooga.github.io", "category": "Developer Tools", "status": 200},
  {"slug": "opacta-de", "name": "opacta", "url": "https://opacta.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://opacta.de/partnerprogramm"},
  {"slug": "open-weights-postlark-ai", "name": "Open Weight Weekly", "url": "https://open-weights.postlark.ai", "category": "AI & Agents", "status": 200},
  {"slug": "openagents-org", "name": "OpenAgents", "url": "https://openagents.org", "category": "AI & Agents", "status": 200, "partnerPortal": "https://openagents.org/partners", "docs": "https://openagents.org/docs/en/getting-started/overview"},
  {"slug": "openapps-pro", "name": "Open Apps", "url": "https://openapps.pro", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://openapps.pro/partners", "docs": "https://openapps.pro/docs"},
  {"slug": "openclaw-ai", "name": "OpenClaw", "url": "https://openclaw.ai", "category": "Compliance & KYC", "status": 200, "docs": "https://docs.openclaw.ai"},
  {"slug": "openclawlaunch-com", "name": "OpenClaw Launch", "url": "https://openclawlaunch.com", "category": "Cloud & Infrastructure", "status": 200, "partnerPortal": "https://openclawlaunch.com/partners", "docs": "https://openclawlaunch.com/?login=1&callbackUrl=%2Fdevelopers"},
  {"slug": "opendevin-com", "name": "opendevin.com for sale", "url": "https://opendevin.com", "category": "Developer Tools", "status": 200},
  {"slug": "openeden-com", "name": "Openeden", "url": "https://openeden.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.openeden.com"},
  {"slug": "openfund-com", "name": "Trade without limits", "url": "https://openfund.com", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://openfund.com/partners", "docs": "https://openfund.com/docs"},
  {"slug": "opengpt-x-de", "name": "OpenGPT-X", "url": "https://opengpt-x.de", "category": "AI & Agents", "status": 200, "partnerPortal": "https://opengpt-x.de/en/partners"},
  {"slug": "openhands-dev", "name": "OpenHands", "url": "https://www.openhands.dev", "category": "Cloud & Infrastructure", "status": 200, "docs": "https://docs.openhands.dev/overview/introduction"},
  {"slug": "openinterpreter-com", "name": "Open Interpreter", "url": "https://www.openinterpreter.com", "category": "AI & Agents", "status": 200, "docs": "https://www.openinterpreter.com/docs/terminal"},
  {"slug": "openobserve-ai", "name": "OpenObserve â Open Source Observability Platform", "url": "https://openobserve.ai", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://openobserve.ai/partners", "docs": "https://openobserve.ai/docs"},
  {"slug": "openpayd-com", "name": "OpenPayd", "url": "https://www.openpayd.com", "category": "Finance & Banking", "status": 200},
  {"slug": "openrouter-ai", "name": "OpenRouter", "url": "https://openrouter.ai", "category": "AI & Agents", "status": 200, "partnerPortal": "https://openrouter.ai/works-with-openrouter", "docs": "https://openrouter.ai/docs/quickstart"},
  {"slug": "opensats-org", "name": "OpenSats", "url": "https://opensats.org", "category": "Government & Institutions", "status": 200},
  {"slug": "opensearch-org", "name": "Opensearch", "url": "https://opensearch.org", "category": "Government & Institutions", "status": 200, "docs": "https://docs.opensearch.org/latest/index.html"},
  {"slug": "opensre-com", "name": "OpenSRE", "url": "https://www.opensre.com", "category": "AI & Agents", "status": 200, "docs": "https://www.opensre.com/docs"},
  {"slug": "opentelemetry-io", "name": "OpenTelemetry", "url": "https://opentelemetry.io", "category": "Ecosystem & Portale", "status": 200, "docs": "https://opentelemetry.io/docs"},
  {"slug": "openthoughts-ai", "name": "OpenThoughts", "url": "https://www.openthoughts.ai", "category": "AI & Agents", "status": 200},
  {"slug": "openwebui-com", "name": "Open WebUI: Self-Hosted AI Platform", "url": "https://openwebui.com", "category": "Cloud & Infrastructure", "status": 200, "docs": "https://docs.openwebui.com"},
  {"slug": "openzeppelin-com", "name": "OpenZeppelin", "url": "https://www.openzeppelin.com", "category": "Finance & Banking", "status": 200, "docs": "https://docs.openzeppelin.com"},
  {"slug": "orchidea-dev", "name": "Orchidea", "url": "https://www.orchidea.dev", "category": "Developer Tools", "status": 200},
  {"slug": "parlament-ch", "name": "Schweizer Parlament", "url": "https://www.parlament.ch/de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "partner-charta-de", "name": "CHARTA &#8211; Börse für Versicherungen AG", "url": "https://partner.charta.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "partner-io", "name": "Partner Management Software for SaaS", "url": "https://www.partner.io", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "partnerplace-io", "name": "Grow your partner network. Faster.", "url": "https://partnerplace.io", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "partnerplatform-bol-com", "name": "Welkom op het Partnerplatform!", "url": "https://partnerplatform.bol.com/nl", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://partnerplatform.bol.com/nl/partners", "docs": "https://partnerplatform.bol.com/nl/docs"},
  {"slug": "partnerportal-io", "name": "Partner Portal & PRM Software", "url": "https://www.partnerportal.io", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.partnerportal.io/partner-program", "docs": "https://docs.partnerportal.io"},
  {"slug": "partnersgroup-com", "name": "A leading global private markets firm", "url": "https://www.partnersgroup.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "pay-collectnexchange-com", "name": "AFSA-Licensed Digital Asset Services", "url": "https://collectnexchange.com", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://collectnexchange.com/partners"},
  {"slug": "pickyourtech-com", "name": "Discover curated open-source projects & SaaS alternatives", "url": "https://www.pickyourtech.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "pictet-com", "name": "Pictet Belgique", "url": "https://www.pictet.com/be/fr", "category": "Finance & Banking", "status": 200},
  {"slug": "pimcore-com", "name": "The Future of Data & Experience Management", "url": "https://pimcore.com/en", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://pimcore.com/en/partners/find-a-solution-partner", "docs": "https://pimcore.com/en"},
  {"slug": "plaid-com", "name": "Plaid: Enabling all companies to build fintech solutions", "url": "https://plaid.com/en-eu", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://plaid.com/en-eu/partners", "docs": "https://plaid.com/docs"},
  {"slug": "platform-itc-cluster-com", "name": "COOPERATION PLATFORM", "url": "https://platform.itc-cluster.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "plumenetwork-xyz", "name": "Plume", "url": "https://www.plume.org", "category": "Finance & Banking", "status": 200, "docs": "https://docs.plume.org/plume"},
  {"slug": "polygon-technology", "name": "Polygon", "url": "https://polygon.technology", "category": "Finance & Banking", "status": 200, "docs": "https://docs.polygon.technology"},
  {"slug": "privy-io", "name": "Privy", "url": "https://www.privy.io", "category": "Finance & Banking", "status": 200, "docs": "https://docs.privy.io"},
  {"slug": "produktionsallianz-de", "name": "Produktionsallianz", "url": "https://produktionsallianz.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://produktionsallianz.de/partnerschaft-statt-konfrontation", "docs": "https://produktionsallianz.de/anmelden"},
  {"slug": "prometheus-io", "name": "Prometheus", "url": "https://prometheus.io", "category": "Observability & Monitoring", "status": 200, "docs": "https://prometheus.io/docs/introduction/overview"},
  {"slug": "prototype-club", "name": "Open Innovation", "url": "https://www.prototype.club", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.prototype.club/partners"},
  {"slug": "pydantic-dev", "name": "Pydantic", "url": "https://pydantic.dev", "category": "AI & Agents", "status": 200, "docs": "https://pydantic.dev/docs"},
  {"slug": "pygpt-net", "name": "PyGPT", "url": "https://pygpt.net", "category": "AI & Agents", "status": 200},
  {"slug": "qonto-com", "name": "Manage all your finances from your Qonto business account", "url": "https://qonto.com/en", "category": "Finance & Banking", "status": 200, "docs": "https://docs.qonto.com/introduction/welcome"},
  {"slug": "ragflow-io", "name": "RAGFlow", "url": "https://ragflow.io", "category": "Ecosystem & Portale", "status": 200, "docs": "https://ragflow.io/docs"},
  {"slug": "refinitiv-com", "name": "LSEG Data & Analytics", "url": "https://www.lseg.com/en/data-analytics", "category": "Observability & Monitoring", "status": 200},
  {"slug": "regisum-com", "name": "Hostinger Horizons", "url": "https://regisum.com", "category": "Cloud & Infrastructure", "status": 200, "partnerPortal": "https://regisum.com/partners", "docs": "https://regisum.com/docs"},
  {"slug": "regium-io", "name": "REGIUM", "url": "https://www.regium.io", "category": "Compliance & KYC", "status": 200},
  {"slug": "regulix-ai", "name": "Regulix", "url": "https://regulix.ai", "category": "Compliance & KYC", "status": 200},
  {"slug": "relatedrepos-com", "name": "Related Repos", "url": "https://relatedrepos.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "replicate-com", "name": "Replicate", "url": "https://replicate.com", "category": "AI & Agents", "status": 200, "docs": "https://replicate.com/docs"},
  {"slug": "research-in-germany-org", "name": "Research in Germany", "url": "https://www.research-in-germany.org", "category": "Government & Institutions", "status": 200},
  {"slug": "research-rowa-fi", "name": "Where Institutional Capital Goes Next", "url": "https://research.rowa.fi", "category": "Finance & Banking", "status": 200},
  {"slug": "resources-theglobalfund-org", "name": "Country Resources", "url": "https://resources.theglobalfund.org/en", "category": "Finance & Banking", "status": 200},
  {"slug": "riverbed-com", "name": "Optimize Digital Experiences with AI Observability", "url": "https://www.riverbed.com", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://www.riverbed.com/partners", "docs": "https://www.riverbed.com"},
  {"slug": "rowa-fi", "name": "ROWA", "url": "https://rowa.fi", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://rowa.fi/partners", "docs": "https://rowa.fi/docs"},
  {"slug": "rwaatlas-org", "name": "RWA Atlas", "url": "https://rwaatlas.org", "category": "Finance & Banking", "status": 200},
  {"slug": "saarland-ihk-de", "name": "IHK Saarland", "url": "https://saarland.ihk.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "safe-global", "name": "Multisig Wallet for Secure Onchain Asset Management", "url": "https://safe.global", "category": "Finance & Banking", "status": 200, "docs": "https://docs.safe.global"},
  {"slug": "sanctionscanner-com", "name": "Sanction Scanner: Anti-Money Laundering Solutions", "url": "https://www.sanctionscanner.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.sanctionscanner.com/partners", "docs": "https://developer.sanctionscanner.com/en/home-page"},
  {"slug": "scads-ai", "name": "ScaDS.AI Dresden/Leipzig", "url": "https://scads.ai", "category": "AI & Agents", "status": 200},
  {"slug": "scholar-googleusercontent-com", "name": "Google Scholar", "url": "https://scholar.google.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "schwaebische-de", "name": "Regionale und lokale Nachrichten aus Baden-Württemberg", "url": "https://www.schwaebische.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://partner.schwaebische.de"},
  {"slug": "scorechain-com", "name": "Crypto AML Compliance & Blockchain Analytics Platform", "url": "https://www.scorechain.com", "category": "Compliance & KYC", "status": 200, "partnerPortal": "https://www.scorechain.com/partners", "docs": "https://docs.scorechain.com"},
  {"slug": "se-gruppe-de", "name": "Startseite", "url": "https://www.se-gruppe.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.se-gruppe.de/partner-werden"},
  {"slug": "se-legal-de", "name": "Schlun & Elseven Rechtsanwälte", "url": "https://se-legal.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://se-legal.de/rechtsanwalt/gesellschaftsrecht/partnerschaften-in-offenen-handelsgesellschaften-kommanditgesellschaften"},
  {"slug": "search02-weltwaerts-de", "name": "Freiwilligendienst im Ausland mit weltwärts", "url": "https://search02.weltwaerts.de/de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "securitize-io", "name": "Securitize", "url": "https://securitize.io", "category": "Tokenization & Web3", "status": 200},
  {"slug": "selfhostyourself-com", "name": "SelfHostYourself", "url": "https://selfhostyourself.com", "category": "Finance & Banking", "status": 200},
  {"slug": "sensu-io", "name": "Sensu", "url": "https://sensu.io", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://sensu.io/partners", "docs": "https://docs.sensu.io"},
  {"slug": "settlemint-com", "name": "Settlemint", "url": "https://www.settlemint.com", "category": "Compliance & KYC", "status": 200, "docs": "https://docs.settlemint.com/docs"},
  {"slug": "sgpo-gov-sg", "name": "Sgpo", "url": "https://www.sgpo.gov.sg", "category": "Government & Institutions", "status": 200},
  {"slug": "shuftipro-com", "name": "Top Identity Verification and KYC Platform", "url": "https://shuftipro.com", "category": "Compliance & KYC", "status": 200, "partnerPortal": "https://shuftipro.com/partner-program", "docs": "https://shuftipro.com/developers"},
  {"slug": "signoz-io", "name": "SigNoz", "url": "https://signoz.io", "category": "Observability & Monitoring", "status": 200, "docs": "https://signoz.io/docs/introduction"},
  {"slug": "siliconsnark-com", "name": "SiliconSnark", "url": "https://www.siliconsnark.com", "category": "AI & Agents", "status": 200},
  {"slug": "skywalking-apache-org", "name": "Apache SkyWalking â Observability for cloud-native and AI", "url": "https://skywalking.apache.org", "category": "Observability & Monitoring", "status": 200, "docs": "https://skywalking.apache.org/docs"},
  {"slug": "slator-com", "name": "Market intelligence for language solutions and AI", "url": "https://slator.com", "category": "AI & Agents", "status": 200, "partnerPortal": "https://slator.com/partnership-between-gelato-and-xplanation-simplifies-translations-and-printing-for-global-companies"},
  {"slug": "smithery-ai", "name": "Smithery", "url": "https://smithery.ai", "category": "AI & Agents", "status": 200, "docs": "https://smithery.ai/docs"},
  {"slug": "snapshot-box", "name": "Snapshot", "url": "https://snapshot.box", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.snapshot.box"},
  {"slug": "snapshot-org", "name": "Snapshot", "url": "https://snapshot.org", "category": "Government & Institutions", "status": 200, "docs": "https://docs.snapshot.box"},
  {"slug": "softr-io", "name": "Softr", "url": "https://www.softr.io", "category": "AI & Agents", "status": 200, "partnerPortal": "https://www.softr.io/partners", "docs": "https://docs.softr.io"},
  {"slug": "softwareallianz-de", "name": "Finden Sie ihre IT-Experten", "url": "https://softwareallianz.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://softwareallianz.de/partnerschaft"},
  {"slug": "solarisgroup-com", "name": "Empowering you to offer financial services", "url": "https://www.solarisgroup.com/en", "category": "Developer Tools", "status": 200, "partnerPortal": "https://www.solarisgroup.com/en/partners", "docs": "https://docs.solarisgroup.com"},
  {"slug": "sovereign-tech", "name": "Sovereign", "url": "https://www.sovereign.tech", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "sovfin-ai", "name": "Sovfin", "url": "https://www.sovfin.ai", "category": "AI & Agents", "status": 200},
  {"slug": "sovreign-io", "name": "Sovreign", "url": "https://www.sovreign.io", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "spiko-io", "name": "Spiko", "url": "https://www.spiko.io", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.spiko.io"},
  {"slug": "splunk-com", "name": "Splunk", "url": "https://www.splunk.com", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://www.splunk.com/en_us/partners.html", "docs": "https://dev.splunk.com"},
  {"slug": "squads-so", "name": "Squads", "url": "https://squads.xyz", "category": "Finance & Banking", "status": 200, "docs": "https://docs.squads.so/main"},
  {"slug": "squaredup-com", "name": "SquaredUp", "url": "https://squaredup.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://squaredup.com/partners", "docs": "https://docs.squaredup.com"},
  {"slug": "ssctech-com", "name": "SS&C Technologies", "url": "https://www.ssctech.com", "category": "Finance & Banking", "status": 200, "docs": "https://developer.ssctech.com/index.html"},
  {"slug": "stakeholders-cem-wave-eu", "name": "CEM-WAVE", "url": "https://stakeholders.cem-wave.eu", "category": "Government & Institutions", "status": 200},
  {"slug": "startupeuropepartnership-eu", "name": "Startup Europe Partnership (SEP)", "url": "https://startupeuropepartnership.eu", "category": "Government & Institutions", "status": 200},
  {"slug": "startupregions-eu", "name": "Startup Europe Regions Network", "url": "https://startupregions.eu", "category": "Government & Institutions", "status": 200},
  {"slug": "stokr-io", "name": "STOKR", "url": "https://stokr.io", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://stokr.io/partners", "docs": "https://stokr.io/docs"},
  {"slug": "striga-com", "name": "Payments infrastructure for Bitcoin and Stablecoins", "url": "https://striga.com", "category": "Finance & Banking", "status": 200, "docs": "https://docs.striga.com/reference/getting-started-with-your-api"},
  {"slug": "stripe-com", "name": "Stripe", "url": "https://stripe.com/nl-be", "category": "Cloud & Infrastructure", "status": 200, "partnerPortal": "https://stripe.com/nl-be/partners", "docs": "https://docs.stripe.com"},
  {"slug": "sumologic-com", "name": "Cloud log management, monitoring, SIEM tools Sumo Logic", "url": "https://www.sumologic.com:443", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://www.sumologic.com:443/partners", "docs": "https://www.sumologic.com/help/docs"},
  {"slug": "sumsub-com", "name": "Leading Identity Verification Service", "url": "https://sumsub.com", "category": "Compliance & KYC", "status": 200, "partnerPortal": "https://sumsub.com/partners", "docs": "https://docs.sumsub.com"},
  {"slug": "supabase-com", "name": "Supabase", "url": "https://supabase.com", "category": "Developer Tools", "status": 200, "partnerPortal": "https://supabase.com/partners", "docs": "https://supabase.com/docs"},
  {"slug": "superagi-com", "name": "SuperAGI", "url": "https://superagi.com", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.superagi.com"},
  {"slug": "superstate-co", "name": "Superstate", "url": "https://superstate.com", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://superstate.com/partners", "docs": "https://docs.superstate.com"},
  {"slug": "supportcso-unpartnerportal-org", "name": "United Nations Partner Portal", "url": "https://supportcso.unpartnerportal.org/hc/en-us", "category": "Government & Institutions", "status": 200},
  {"slug": "svcf-org", "name": "Svcf", "url": "https://www.svcf.org", "category": "Government & Institutions", "status": 200, "partnerPortal": "https://www.svcf.org", "docs": "https://www.svcf.org"},
  {"slug": "swfi-com", "name": "Sovereign Wealth Fund Institute", "url": "https://www.swfi.com", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://www.swfi.com/partners", "docs": "https://www.swfi.com/docs"},
  {"slug": "swisscom-com", "name": "Swisscom Privatkunden: Mobile, TV, Internet & Festnetz", "url": "https://www.swisscom.ch/de/privatkunden.html", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.swisscom.ch/de/privatkunden.html/partners", "docs": "https://www.swisscom.ch/cloudnative"},
  {"slug": "sydecar-io", "name": "Sydecar", "url": "https://sydecar.io", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "synaplan-com", "name": "Synaplan", "url": "https://www.synaplan.com", "category": "AI & Agents", "status": 200, "docs": "https://docs.synaplan.com"},
  {"slug": "syndicate-io", "name": "Syndicate", "url": "https://syndicate.io", "category": "Ecosystem & Portale", "status": 200, "docs": "https://docs.syndicate.io/en"},
  {"slug": "tagesschau-de", "name": "tagesschau.de", "url": "https://www.tagesschau.de:443", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "tally-xyz", "name": "Cactus", "url": "https://www.tally.xyz", "category": "Tokenization & Web3", "status": 200, "docs": "https://docs.tally.xyz"},
  {"slug": "taurusgroup-ch", "name": "Digital Asset Infrastructure for Financial Institutions", "url": "https://www.taurushq.com", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://www.taurushq.com/partners", "docs": "https://www.taurushq.com/docs"},
  {"slug": "taxprofblog-aals-org", "name": "TaxProf Blog &#8226; Association of American Law Schools", "url": "https://taxprofblog.aals.org", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://taxprofblog.aals.org/2010/05/05/partnership"},
  {"slug": "techsy-io", "name": "AI & Software Development", "url": "https://techsy.io/en", "category": "AI & Agents", "status": 200, "partnerPortal": "https://techsy.io/en/partners"},
  {"slug": "telekom-com", "name": "Corporate Website: Information about the Group", "url": "https://www.telekom.com:443", "category": "Ecosystem & Portale", "status": 200, "docs": "https://developer.telekom.com/de"},
  {"slug": "temps-sh", "name": "Replace 7 SaaS Tools With One Self-Hosted Platform", "url": "https://temps.sh", "category": "Cloud & Infrastructure", "status": 200, "docs": "https://temps.sh/docs/quickstart"},
  {"slug": "thanos-io", "name": "Thanos", "url": "https://thanos.io", "category": "Observability & Monitoring", "status": 200},
  {"slug": "thedonorsfund-org", "name": "The Donors Fund", "url": "https://thedonorsfund.org", "category": "Finance & Banking", "status": 200},
  {"slug": "theledgermind-com", "name": "LedgerMind &#8211; AI-Powered Market Intelligence", "url": "https://theledgermind.com", "category": "Finance & Banking", "status": 200},
  {"slug": "thenextweb-com", "name": "TNW", "url": "https://thenextweb.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "thesovereign-fun", "name": "The Sovereign Capital Reserve", "url": "https://www.thesovereign.fun", "category": "Finance & Banking", "status": 200},
  {"slug": "thesovereignnetwork-org", "name": "The Sovereign Network", "url": "https://www.thesovereignnetwork.org", "category": "Government & Institutions", "status": 200, "partnerPortal": "https://www.thesovereignnetwork.org/partners", "docs": "https://www.thesovereignnetwork.org/docs"},
  {"slug": "tink-com", "name": "Tink", "url": "https://tink.com", "category": "Finance & Banking", "status": 200, "docs": "https://docs.tink.com"},
  {"slug": "tmf-group-com", "name": "Tmf Group", "url": "https://www.tmf-group.com", "category": "Compliance & KYC", "status": 200},
  {"slug": "tndeptofhealth-caspio-app", "name": "Tndeptofhealth", "url": "https://tndeptofhealth.caspio.app", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://tndeptofhealth.caspio.app/partners", "docs": "https://tndeptofhealth.caspio.app/docs"},
  {"slug": "together-ai", "name": "Together AI", "url": "https://www.together.ai", "category": "Cloud & Infrastructure", "status": 200, "docs": "https://docs.together.ai/intro"},
  {"slug": "tokenkickstarter-com", "name": "\\\\u26a0\\\\ufe0f Security Warning", "url": "https://www.tokenkickstarter.com", "category": "Tokenization & Web3", "status": 200, "docs": "https://www.tokenkickstarter.com/docs"},
  {"slug": "tokentoolhub-com", "name": "Tokentoolhub", "url": "https://tokentoolhub.com", "category": "Tokenization & Web3", "status": 200, "partnerPortal": "https://tokentoolhub.com/partner-program"},
  {"slug": "tokeny-com", "name": "Tokeny &#8211; The Leading Onchain Finance Operating System", "url": "https://tokeny.com", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://tokeny.com/partners", "docs": "https://docs.tokeny.com"},
  {"slug": "toucans-ecdao-org", "name": "Toucans", "url": "https://toucans.ecdao.org", "category": "Tokenization & Web3", "status": 200},
  {"slug": "transak-com", "name": "Crypto Payment Rail for Financial Applications", "url": "https://transak.com", "category": "Finance & Banking", "status": 200, "docs": "https://docs.transak.com/getting-started/what-is-transak"},
  {"slug": "treasury-ripple-com", "name": "Ripple Treasury, Powered by GTreasury", "url": "https://treasury.ripple.com", "category": "Finance & Banking", "status": 200, "partnerPortal": "https://treasury.ripple.com/company/partners"},
  {"slug": "trezu-org", "name": "Trezu â One multisig. Any crypto. Confidential.", "url": "https://trezu.org", "category": "Tokenization & Web3", "status": 200, "docs": "https://docs.trezu.org/home"},
  {"slug": "trmlabs-com", "name": "TRM Labs", "url": "https://www.trmlabs.com", "category": "AI & Agents", "status": 200, "partnerPortal": "https://www.trmlabs.com/partners", "docs": "https://docs.trmlabs.com"},
  {"slug": "turnkey-com", "name": "Turnkey", "url": "https://www.turnkey.com", "category": "Cloud & Infrastructure", "status": 200, "docs": "https://docs.turnkey.com/welcome"},
  {"slug": "unocha-org", "name": "Unocha", "url": "https://unocha.org", "category": "Government & Institutions", "status": 202, "partnerPortal": "https://unocha.org/partners", "docs": "https://www.unocha.org"},
  {"slug": "unpartnerportal-org", "name": "UN Partner Portal", "url": "https://www.unpartnerportal.org", "category": "Government & Institutions", "status": 200, "partnerPortal": "https://www.unpartnerportal.org/partners", "docs": "https://www.unpartnerportal.org/docs"},
  {"slug": "unternehmen-integrieren-fluechtlinge-de", "name": "Startseite", "url": "https://www.unternehmen-integrieren-fluechtlinge.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "upstreamapp-com", "name": "Upstream", "url": "https://upstreamapp.com", "category": "Tokenization & Web3", "status": 200},
  {"slug": "uptime-kuma-pet", "name": "Uptime Kuma", "url": "https://uptime.kuma.pet", "category": "Observability & Monitoring", "status": 200, "docs": "https://github.com/louislam/uptime-kuma/wiki"},
  {"slug": "usecarly-com", "name": "Carly AI", "url": "https://www.usecarly.com", "category": "AI & Agents", "status": 200, "partnerPortal": "https://www.usecarly.com/partner", "docs": "https://www.usecarly.com/developers"},
  {"slug": "utopialabs-com", "name": "Utopia Labs", "url": "https://www.utopialabs.com", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "vanquishsolutions-us", "name": "Vanquish", "url": "https://www.vanquishsolutions.us", "category": "Finance & Banking", "status": 200},
  {"slug": "vbg-de", "name": "VBG", "url": "https://www.vbg.de/cms", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "vdi-de", "name": "Verein Deutscher Ingenieure e.V.", "url": "https://www.vdi.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.vdi.de/mitgliedschaft/login?redirect_url=https%3A%2F%2Fwww.vdi.de%2Fintern%2Fmitgliedervorteile%2Fvorteilsportal&cHash=d9e3095f60d1ff24ee99392f3c62d092"},
  {"slug": "vector-dev", "name": "Vector", "url": "https://vector.dev", "category": "Observability & Monitoring", "status": 200, "docs": "https://vector.dev/docs"},
  {"slug": "vedicdao-com", "name": "Vedic DAO", "url": "https://www.vedicdao.com", "category": "Finance & Banking", "status": 200},
  {"slug": "veriff-com", "name": "Global AI Identity Verification & KYC Solutions", "url": "https://www.veriff.com", "category": "Compliance & KYC", "status": 200},
  {"slug": "victoriametrics-com", "name": "VictoriaMetrics: Simple, Reliable & Efficient Observability", "url": "https://victoriametrics.com", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://victoriametrics.com/partners/index.html", "docs": "https://docs.victoriametrics.com"},
  {"slug": "vllm-ai", "name": "vLLM", "url": "https://vllm.ai", "category": "AI & Agents", "status": 200, "docs": "https://docs.vllm.ai/en/latest"},
  {"slug": "vodafone-de", "name": "Vodafone", "url": "https://www.vodafone.de", "category": "Ecosystem & Portale", "status": 200, "partnerPortal": "https://www.vodafone.de/business/business-partner-programm", "docs": "https://www.vodafone.de"},
  {"slug": "voltlegal-com", "name": "VoltLegal", "url": "https://voltlegal.com", "category": "Finance & Banking", "status": 200},
  {"slug": "vstorm-co", "name": "The Leading Agentic AI Company", "url": "https://vstorm.co", "category": "AI & Agents", "status": 200, "partnerPortal": "https://vstorm.co", "docs": "https://vstorm.co"},
  {"slug": "xai-lab-net", "name": "xAI Lab, University of Marburg", "url": "https://xai-lab.net", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "yapily-com", "name": "Yapily", "url": "https://www.yapily.com", "category": "Finance & Banking", "status": 200, "docs": "https://docs.yapily.com/introduction"},
  {"slug": "zabbix-com", "name": "Zabbix", "url": "https://www.zabbix.com", "category": "Observability & Monitoring", "status": 200, "partnerPortal": "https://www.zabbix.com/partners", "docs": "https://www.zabbix.com/page404"},
  {"slug": "zaneops-dev", "name": "Welcome", "url": "https://zaneops.dev", "category": "Developer Tools", "status": 200},
  {"slug": "zdfheute-de", "name": "ZDFheute", "url": "https://www.zdfheute.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "zeffy-com", "name": "Zeffy", "url": "https://www.zeffy.com", "category": "Finance & Banking", "status": 200, "docs": "https://support.zeffy.com"},
  {"slug": "zipkin-io", "name": "OpenZipkin &middot; A distributed tracing system", "url": "https://zipkin.io", "category": "Developer Tools", "status": 200},
  {"slug": "zivilgesellschaft-ist-gemeinnuetzig-de", "name": "Zivilgesellschaft ist gemeinnützig", "url": "https://www.zivilgesellschaft-ist-gemeinnuetzig.de", "category": "Ecosystem & Portale", "status": 200},
  {"slug": "zoniqx-com", "name": "HomePage", "url": "https://www.zoniqx.com", "category": "Ecosystem & Portale", "status": 200},
];

export const validatedCategories = Array.from(
  new Set(validatedDirectory.map((e) => e.category)),
).sort();

/** Domain oder Firmenname gegen das live gepruefte Verzeichnis abgleichen. */
export function lookupValidated(input: string): ValidatedEntry | null {
  const q = input.trim().toLowerCase().replace(/^https?:\/\//, "").replace(/^www\./, "").replace(/\/.*$/, "");
  if (!q) return null;
  return (
    validatedDirectory.find((e) => e.url.toLowerCase().includes(q) || e.slug === q.replace(/[^a-z0-9]+/g, "-")) ??
    validatedDirectory.find((e) => e.name.toLowerCase().includes(q)) ??
    null
  );
}

/** Aehnliche Anbieter aus derselben Kategorie (echte, validierte Domains). */
export function similarTo(slug: string, limit = 111): ValidatedEntry[] {
  const base = validatedDirectory.find((e) => e.slug === slug);
  if (!base) return [];
  return validatedDirectory.filter((e) => e.slug !== slug && e.category === base.category).slice(0, limit);
}
